---
title: "2025 GitHub Trends — All Repositories"
layout: default
---

# All repositories (by stars)

- [openclaw/openclaw](repos/openclaw-openclaw.md) · ⭐ 309403 · TypeScript · A comprehensive open-source AI agent ecosystem for cross-platform autonomous ...

- [x1xhlol/system-prompts-and-models-of-ai-tools](repos/x1xhlol-system-prompts-and-models-of-ai-tools.md) · ⭐ 130630 · — · A high-quality repository of curated system prompts and AI model configuratio...

- [anomalyco/opencode](repos/anomalyco-opencode.md) · ⭐ 121307 · TypeScript · A secure, local-first AI coding assistant for automated refactoring and codeb...

- [google-gemini/gemini-cli](repos/google-gemini-gemini-cli.md) · ⭐ 97506 · TypeScript · The official Google-built terminal agent for high-performance Gemini model in...

- [anthropics/skills](repos/anthropics-skills.md) · ⭐ 92402 · Python · Anthropic's official collection of modular skills to extend Claude's task-spe...

- [deepseek-ai/DeepSeek-R1](repos/deepseek-ai-deepseek-r1.md) · ⭐ 91967 · — · State-of-the-art open reasoning models incentivized via reinforcement learnin...

- [obra/superpowers](repos/obra-superpowers.md) · ⭐ 80880 · Shell · A high-performance toolkit for building and orchestrating complex multi-agent...

- [anthropics/claude-code](repos/anthropics-claude-code.md) · ⭐ 77390 · Shell · Anthropic's high-speed agentic CLI for secure and accurate software development.

- [github/spec-kit](repos/github-spec-kit.md) · ⭐ 76396 · Python · A standardized framework for defining, documenting, and evaluating AI agent c...

- [affaan-m/everything-claude-code](repos/affaan-m-everything-claude-code.md) · ⭐ 74106 · JavaScript · A comprehensive community resource and guide for mastering Claude Code optimi...

- [openai/codex](repos/openai-codex.md) · ⭐ 65014 · Rust · Foundational code generation research repository demonstrating OpenAI's Codex...

- [FoundationAgents/OpenManus](repos/foundationagents-openmanus.md) · ⭐ 55203 · Python · An autonomous AI agent for universal digital task execution and deep research.

- [Zie619/n8n-workflows](repos/zie619-n8n-workflows.md) · ⭐ 52866 · Python · Curated collection of industry-standard n8n workflows for advanced AI automat...

- [upstash/context7](repos/upstash-context7.md) · ⭐ 48830 · TypeScript · Edge-optimized context management library for ultra-fast, smart LLM context h...

- [sansan0/TrendRadar](repos/sansan0-trendradar.md) · ⭐ 48817 · Python · An AI agent system that autonomously tracks tech trends and generates strateg...

- [karpathy/nanochat](repos/karpathy-nanochat.md) · ⭐ 47610 · Python · Andrej Karpathy's minimal, single-file reference for modern AI chat and tool-...

- [OpenCut-app/OpenCut](repos/opencut-app-opencut.md) · ⭐ 46530 · TypeScript · A natural language-driven AI video editor for automated cutting, captioning, ...

- [ComposioHQ/awesome-claude-skills](repos/composiohq-awesome-claude-skills.md) · ⭐ 43600 · Python · A definitive curated list of industry-level skillsets and integrations to hyp...

- [nextlevelbuilder/ui-ux-pro-max-skill](repos/nextlevelbuilder-ui-ux-pro-max-skill.md) · ⭐ 40724 · Python · Pixel-perfect UI/UX aesthetic rules for AI-driven frontend generation.

- [bmad-code-org/BMAD-METHOD](repos/bmad-code-org-bmad-method.md) · ⭐ 40467 · JavaScript · An agile architecture framework for multi-agent autonomous software developme...

- [code-yeongyu/oh-my-openagent](repos/code-yeongyu-oh-my-openagent.md) · ⭐ 39639 · TypeScript · A modular, theme-and-plugin-oriented configuration framework for managing AI ...

- [tw93/Mole](repos/tw93-mole.md) · ⭐ 39524 · Shell · A minimalist, semantic web scraper that converts any webpage into clean JSON/...

- [msitarzewski/agency-agents](repos/msitarzewski-agency-agents.md) · ⭐ 37142 · Shell · A specialized multi-agent framework patterned after high-efficiency team stru...

- [koala73/worldmonitor](repos/koala73-worldmonitor.md) · ⭐ 37019 · TypeScript · AI-driven real-time global information monitoring and anomaly detection platf...

- [VoltAgent/awesome-openclaw-skills](repos/voltagent-awesome-openclaw-skills.md) · ⭐ 36669 · — · The definitive directory of community-built and official skills for the OpenC...

- [ruvnet/RuView](repos/ruvnet-ruview.md) · ⭐ 35949 · Rust · Real-time AI visual analysis platform optimized for low-resource edge devices.

- [google/langextract](repos/google-langextract.md) · ⭐ 34668 · Python · Google's high-accuracy machine learning tool for multilingual language identi...

- [thedotmack/claude-mem](repos/thedotmack-claude-mem.md) · ⭐ 34477 · TypeScript · A local knowledge-graph-based memory extension for Claude AI to sustain long-...

- [asgeirtj/system_prompts_leaks](repos/asgeirtj-system-prompts-leaks.md) · ⭐ 34243 · HTML · Archive and research repository for discovered system prompts of major AI pla...

- [KeygraphHQ/shannon](repos/keygraphhq-shannon.md) · ⭐ 33384 · TypeScript · A semantic network protocol designed to compress LLM inputs and reduce API co...

- [HKUDS/nanobot](repos/hkuds-nanobot.md) · ⭐ 33082 · Python · A lightweight 'micro-agent' framework optimized for extremely low-memory envi...

- [wshobson/agents](repos/wshobson-agents.md) · ⭐ 31135 · Python · High-performance AI conversation server supporting real-time text and voice i...

- [Fission-AI/OpenSpec](repos/fission-ai-openspec.md) · ⭐ 30128 · TypeScript · An open-source interoperability protocol for AI agents to share and invoke cr...

- [bytedance/deer-flow](repos/bytedance-deer-flow.md) · ⭐ 30059 · Python · ByteDance's lightweight, high-concurrency AI task orchestration engine based ...

- [karpathy/autoresearch](repos/karpathy-autoresearch.md) · ⭐ 29930 · Python · Andrej Karpathy's autonomous AI research agent for automated paper ingestion ...

- [musistudio/claude-code-router](repos/musistudio-claude-code-router.md) · ⭐ 29575 · TypeScript · A smart middleware for routing AI tasks to the most cost-effective Claude mod...

- [gsd-build/get-shit-done](repos/gsd-build-get-shit-done.md) · ⭐ 29106 · JavaScript · A high-velocity AI task runner focused on rapid execution and minimal adminis...

- [microsoft/playwright-mcp](repos/microsoft-playwright-mcp.md) · ⭐ 28803 · TypeScript · Microsoft's official MCP server for controlled browser automation via Playwri...

- [bytedance/UI-TARS-desktop](repos/bytedance-ui-tars-desktop.md) · ⭐ 28799 · TypeScript · ByteDance's desktop interface for controlling vision-driven AI agents on loca...

- [ChromeDevTools/chrome-devtools-mcp](repos/chromedevtools-chrome-devtools-mcp.md) · ⭐ 28759 · TypeScript · An official MCP server for AI-driven browser debugging and performance auditi...

- [github/github-mcp-server](repos/github-github-mcp-server.md) · ⭐ 27843 · Go · Official GitHub MCP server for direct AI access to repositories, issues, and ...

- [hesreallyhim/awesome-claude-code](repos/hesreallyhim-awesome-claude-code.md) · ⭐ 27796 · Python · The ultimate community-curated directory of Claude Code plugins, setups, and ...

- [farion1231/cc-switch](repos/farion1231-cc-switch.md) · ⭐ 27614 · Rust · A fast configuration switcher for Claude Code to manage multiple accounts and...

- [datawhalechina/hello-agents](repos/datawhalechina-hello-agents.md) · ⭐ 27265 · Python · A comprehensive, beginner-friendly educational framework for mastering AI age...

- [simstudioai/sim](repos/simstudioai-sim.md) · ⭐ 26988 · TypeScript · A sophisticated multi-modal AI studio for building, orchestrating, and simula...

- [zeroclaw-labs/zeroclaw](repos/zeroclaw-labs-zeroclaw.md) · ⭐ 26645 · Rust · Extreme-performance minimal version of the OpenClaw agent for local system au...

- [huggingface/agents-course](repos/huggingface-agents-course.md) · ⭐ 26281 · MDX · Official Hugging Face curriculum for mastering LLM agents using open-source m...

- [lbjlaq/Antigravity-Manager](repos/lbjlaq-antigravity-manager.md) · ⭐ 26107 · Rust · A robust process manager and monitor for local AI agents and background backg...

- [huggingface/open-r1](repos/huggingface-open-r1.md) · ⭐ 25941 · Python · The community reproduction of DeepSeek-R1 for open-weights reasoning model tr...

- [eyaltoledano/claude-task-master](repos/eyaltoledano-claude-task-master.md) · ⭐ 25902 · JavaScript · Task-oriented UI and automation layer for orchestrating multi-step Claude 3.5...

- [shareAI-lab/learn-claude-code](repos/shareai-lab-learn-claude-code.md) · ⭐ 25791 · TypeScript · In-depth technical tutorials and reverse-engineering notes for mastering Clau...

- [zama-ai/fhevm](repos/zama-ai-fhevm.md) · ⭐ 25701 · Rust · An EVM-compatible blockchain virtual machine that supports computation on enc...

- [Fosowl/agenticSeek](repos/fosowl-agenticseek.md) · ⭐ 25493 · Python · A deep-reasoning autonomous AI search engine for information synthesis and re...

- [permissionlesstech/bitchat](repos/permissionlesstech-bitchat.md) · ⭐ 25352 · Swift · A zero-knowledge, P2P AI chat platform focusing on extreme privacy and local ...

- [apple/container](repos/apple-container.md) · ⭐ 25226 · Swift · Apple's internal-grade lightweight service mesh and dependency injection fram...

- [github/awesome-copilot](repos/github-awesome-copilot.md) · ⭐ 24951 · TypeScript · The authoritative official list of Copilot extensions, enterprise patterns, a...

- [firecrawl/open-lovable](repos/firecrawl-open-lovable.md) · ⭐ 24425 · TypeScript · A design-to-code automation tool that converts live websites into clean, edit...

- [sipeed/picoclaw](repos/sipeed-picoclaw.md) · ⭐ 24415 · Go · Low-footprint 'Micro-Agent' implementation for RISC-V and embedded IoT vision...

- [zai-org/Open-AutoGLM](repos/zai-org-open-autoglm.md) · ⭐ 24268 · Python · Open-source autonomous orchestration and reasoning framework powered by the G...

- [hesamsheikh/awesome-openclaw-usecases](repos/hesamsheikh-awesome-openclaw-usecases.md) · ⭐ 24244 · — · The master collection of practical, real-world implementations and 'Success S...

- [linshenkx/prompt-optimizer](repos/linshenkx-prompt-optimizer.md) · ⭐ 24241 · TypeScript · An automated meta-prompting tool that iterates and refines user prompts for p...

- [sickn33/antigravity-awesome-skills](repos/sickn33-antigravity-awesome-skills.md) · ⭐ 23866 · Python · The central repository for high-performance 'Skills' compatible with the Anti...

- [microsoft/VibeVoice](repos/microsoft-vibevoice.md) · ⭐ 23725 · Python · Microsoft's research project for high-fidelity, emotion-aware AI voice synthe...

- [resemble-ai/chatterbox](repos/resemble-ai-chatterbox.md) · ⭐ 23264 · Python · A decentralized, high-throughput P2P communication bus for autonomous agent s...

- [toon-format/toon](repos/toon-format-toon.md) · ⭐ 23207 · TypeScript · A strictly-typed task definition format designed to ensure zero-ambiguity in ...

- [BloopAI/vibe-kanban](repos/bloopai-vibe-kanban.md) · ⭐ 23092 · Rust · A specialized Kanban board interface for orchestrating and visualizing coding...

- [badlogic/pi-mono](repos/badlogic-pi-mono.md) · ⭐ 23076 · TypeScript · A comprehensive, all-in-one Swiss Army knife for building and deploying AI ag...

- [vercel-labs/agent-skills](repos/vercel-labs-agent-skills.md) · ⭐ 22907 · JavaScript · Vercel's official library of modular, verified skills for building high-perfo...

- [davila7/claude-code-templates](repos/davila7-claude-code-templates.md) · ⭐ 22839 · Python · A configuration management and templating CLI to hyper-optimize Claude Code e...

- [DayuanJiang/next-ai-draw-io](repos/dayuanjiang-next-ai-draw-io.md) · ⭐ 22811 · TypeScript · An AI-powered diagramming assistant that generates and edits Draw.io layouts ...

- [deepseek-ai/DeepSeek-OCR](repos/deepseek-ai-deepseek-ocr.md) · ⭐ 22683 · Python · State-of-the-art vision-to-text 'Optical Compression' model for hyper-accurat...

- [a2aproject/A2A](repos/a2aproject-a2a.md) · ⭐ 22483 · Shell · A universal communication protocol for decentralized, cross-platform AI agent...

- [qwibitai/nanoclaw](repos/qwibitai-nanoclaw.md) · ⭐ 22170 · TypeScript · A secure, containerized 'micro-agent' for cross-platform messaging and task a...

- [vercel-labs/agent-browser](repos/vercel-labs-agent-browser.md) · ⭐ 21519 · Rust · Vercel's high-performance CLI tool for giving AI agents 'Hands and Eyes' in a...

- [paperclipai/paperclip](repos/paperclipai-paperclip.md) · ⭐ 21483 · TypeScript · A radical 'Autonomous Company' framework that orchestrates agents to handle c...

- [oraios/serena](repos/oraios-serena.md) · ⭐ 21442 · Python · A suite of professional MCP servers for high-precision semantic code search a...

- [SuperClaude-Org/SuperClaude_Framework](repos/superclaude-org-superclaude-framework.md) · ⭐ 21410 · Python · A 'Meta-Framework' for Claude Code that injects elite engineering methodologi...

- [VectifyAI/PageIndex](repos/vectifyai-pageindex.md) · ⭐ 21386 · Python · A breakthrough 'Vector-less' RAG system that uses hierarchical indexing and s...

- [PicoTrex/Awesome-Nano-Banana-images](repos/picotrex-awesome-nano-banana-images.md) · ⭐ 21303 · — · An open dataset and showcase for high-consistency, AI-generated character and...

- [OpenListTeam/OpenList](repos/openlistteam-openlist.md) · ⭐ 21302 · Go · A privacy-hardened fork of AList for secure, unified cloud storage management...

- [charmbracelet/crush](repos/charmbracelet-crush.md) · ⭐ 21279 · Go · Charm Bracelet's aesthetic, high-performance TUI coding agent for terminal lu...

- [basecamp/omarchy](repos/basecamp-omarchy.md) · ⭐ 21141 · Shell · Basecamp's optimized, developer-centric Linux distribution for high-performan...

- [usestrix/strix](repos/usestrix-strix.md) · ⭐ 20937 · Python · Autonomous AI penetration testing agents that find and fix security vulnerabi...

- [winfunc/opcode](repos/winfunc-opcode.md) · ⭐ 20905 · TypeScript · A comprehensive GUI and management toolkit for Claude Code, featuring agent o...

- [ruvnet/ruflo](repos/ruvnet-ruflo.md) · ⭐ 20801 · TypeScript · A high-performance orchestration platform for building and deploying complex ...

- [QwenLM/qwen-code](repos/qwenlm-qwen-code.md) · ⭐ 20453 · TypeScript · Alibaba's official terminal-based AI coding agent powered by the Qwen model f...

- [666ghj/MiroFish](repos/666ghj-mirofish.md) · ⭐ 20288 · Python · A minimalist and universal swarm intelligence engine designed for predictive ...

- [coze-dev/coze-studio](repos/coze-dev-coze-studio.md) · ⭐ 20127 · TypeScript · ByteDance's official visual IDE for building, testing, and deploying high-per...

- [enescingoz/awesome-n8n-templates](repos/enescingoz-awesome-n8n-templates.md) · ⭐ 20051 · — · The world's largest collection of open-source n8n automation templates for AI...

- [openai/openai-agents-python](repos/openai-openai-agents-python.md) · ⭐ 19953 · Python · OpenAI's official Python SDK for building modular, provider-agnostic multi-ag...

- [openai/gpt-oss](repos/openai-gpt-oss.md) · ⭐ 19908 · Python · OpenAI's official release of open-weight reasoning and instruction-tuned mode...

- [dyad-sh/dyad](repos/dyad-sh-dyad.md) · ⭐ 19873 · TypeScript · A high-performance local AI app builder that converts prompts into full-stack...

- [googleworkspace/cli](repos/googleworkspace-cli.md) · ⭐ 19740 · Rust · Google's official CLI for managing Workspace services with integrated AI rese...

- [TibixDev/winboat](repos/tibixdev-winboat.md) · ⭐ 19480 · TypeScript · A high-performance Linux compatibility layer for running Windows applications...

- [ZhuLinsen/daily_stock_analysis](repos/zhulinsen-daily-stock-analysis.md) · ⭐ 19404 · Python · A powerful AI-driven stock analysis agent that synthesizes market data, news,...

- [index-tts/index-tts](repos/index-tts-index-tts.md) · ⭐ 19332 · Python · A professional-grade, controllable zero-shot TTS system for industrial-scale ...

- [ayangweb/BongoCat](repos/ayangweb-bongocat.md) · ⭐ 19325 · TypeScript · An adorable, cross-platform interactive desk pet that reacts to user input an...

- [camel-ai/owl](repos/camel-ai-owl.md) · ⭐ 19186 · Python · CAMEL-AI's framework for multi-agent 'Workforce' coordination and real-world ...

- [nari-labs/dia](repos/nari-labs-dia.md) · ⭐ 19173 · Python · Nari-Labs' state-of-the-art TTS model for generating high-fidelity, emotional...

- [stan-smith/FossFLOW](repos/stan-smith-fossflow.md) · ⭐ 19076 · TypeScript · An isometric diagramming tool that converts infrastructure-as-code into stunn...

- [steveyegge/beads](repos/steveyegge-beads.md) · ⭐ 18922 · Go · Steveyegge's dedicated 'Memory Patch' for AI coding agents to improve archite...

- [agentsmd/agents.md](repos/agentsmd-agentsmd.md) · ⭐ 18887 · TypeScript · An open-standard format for project-level AI instructions, ensuring agents ad...

- [humanlayer/12-factor-agents](repos/humanlayer-12-factor-agents.md) · ⭐ 18688 · TypeScript · The 'Twelve-Factor App' equivalent for AI agents, outlining principles for sc...

- [iOfficeAI/AionUi](repos/iofficeai-aionui.md) · ⭐ 18643 · TypeScript · The official high-performance UI components for the Aion agentic operating sy...

- [hsliuping/TradingAgents-CN](repos/hsliuping-tradingagents-cn.md) · ⭐ 18576 · Python · High-performance Chinese financial trading agent suite with native support fo...

- [dzhng/deep-research](repos/dzhng-deep-research.md) · ⭐ 18562 · TypeScript · An autonomous AI research assistant that browses the web to synthesize deep, ...

- [Alibaba-NLP/DeepResearch](repos/alibaba-nlp-deepresearch.md) · ⭐ 18422 · Python · Alibaba's official framework for large-scale document comprehension and auton...

- [google/adk-python](repos/google-adk-python.md) · ⭐ 18334 · Python · Google's modular Python SDK for building, testing, and scaling industrial-gra...

- [NirDiamant/agents-towards-production](repos/nirdiamant-agents-towards-production.md) · ⭐ 18171 · Jupyter Notebook · A professional-level repository documenting industry best practices for build...

- [google-gemini/gemini-fullstack-langgraph-quickstart](repos/google-gemini-gemini-fullstack-langgraph-quickstart.md) · ⭐ 17983 · Jupyter Notebook · An official Google-Gemini template for building full-stack AI agent applicati...

- [virattt/dexter](repos/virattt-dexter.md) · ⭐ 17813 · TypeScript · A lightweight, high-performance 'Worker Pool' framework for delegating massiv...

- [ahujasid/blender-mcp](repos/ahujasid-blender-mcp.md) · ⭐ 17696 · Python · An MCP server enabling AI agents to design, render, and manipulate 3D scenes ...

- [TecharoHQ/anubis](repos/techarohq-anubis.md) · ⭐ 17689 · Go · A multi-agent security suite for automated discovery and threat modeling in c...

- [astral-sh/ty](repos/astral-sh-ty.md) · ⭐ 17677 · Python · Astral's experimental type-safe language for building deterministic behaviors...

- [cjpais/Handy](repos/cjpais-handy.md) · ⭐ 17512 · Rust · A versatile macOS productivity utility that puts a suite of AI-powered comman...

- [lllyasviel/FramePack](repos/lllyasviel-framepack.md) · ⭐ 16665 · Python · A high-performance library for 'Semantically Compressing' video data for AI a...

- [Kilo-Org/kilocode](repos/kilo-org-kilocode.md) · ⭐ 16629 · TypeScript · A real-time, collaborative 'Pair Programming' IDE designed for high-fidelity ...

- [Snapchat/Valdi](repos/snapchat-valdi.md) · ⭐ 16282 · C++ · Snapchat's lightweight, high-performance library for validating and sanitizin...

- [router-for-me/CLIProxyAPI](repos/router-for-me-cliproxyapi.md) · ⭐ 16044 · Go · A universal proxy server that exposes command-line utilities as structured, a...

- [xai-org/x-algorithm](repos/xai-org-x-algorithm.md) · ⭐ 15987 · Rust · xAI's high-performance library for linear algebra and optimization, optimized...

- [OthmanAdi/planning-with-files](repos/othmanadi-planning-with-files.md) · ⭐ 15953 · Python · An AI agent that constructs and manages a 'File-DAG' to execute cross-project...

- [browser-use/web-ui](repos/browser-use-web-ui.md) · ⭐ 15707 · Python · A comprehensive web dashboard for managing and visualizing autonomous browser...

- [AlexsJones/llmfit](repos/alexsjones-llmfit.md) · ⭐ 15695 · Rust · A professional tool for optimizing and 'fitting' AI models to specific hardwa...

- [karpathy/llm-council](repos/karpathy-llm-council.md) · ⭐ 15592 · Python · Karpathy's project for high-precision decision-making through multi-agent deb...

- [Wan-Video/Wan2.1](repos/wan-video-wan21.md) · ⭐ 15563 · Python · An open-source, state-of-the-art video generation model suite by Alibaba supp...

- [microsoft/agent-lightning](repos/microsoft-agent-lightning.md) · ⭐ 15410 · Python · A toolkit by Microsoft that optimizes AI agents utilizing RL and SFT with min...

- [game1024/OpenSpeedy](repos/game1024-openspeedy.md) · ⭐ 15376 · C++ · An open-source Windows utility for modifying and breaking frame rate limitati...

- [microsoft/mcp-for-beginners](repos/microsoft-mcp-for-beginners.md) · ⭐ 15362 · Jupyter Notebook · A comprehensive, beginner-friendly Microsoft curriculum to learn and build Mo...

- [google-ai-edge/gallery](repos/google-ai-edge-gallery.md) · ⭐ 15355 · Kotlin · An official experimental mobile application by Google showcasing the capabili...

- [mindverse/Second-Me](repos/mindverse-second-me.md) · ⭐ 15332 · Python · An open-source platform enabling users to construct an intelligent, personali...

- [iii-hq/iii](repos/iii-hq-iii.md) · ⭐ 15196 · Rust · A unified execution backend framework replacing complex stacks with simple Fu...

- [slopus/happy](repos/slopus-happy.md) · ⭐ 15051 · TypeScript · An open-source mobile and web client facilitating end-to-end encrypted remote...

- [czlonkowski/n8n-mcp](repos/czlonkowski-n8n-mcp.md) · ⭐ 15032 · TypeScript · An MCP server giving AI assistants direct access to the n8n automation platfo...

- [tobi/qmd](repos/tobi-qmd.md) · ⭐ 14951 · TypeScript · A local, completely on-device AI search engine utilizing BM25 and vector sear...

- [AsyncFuncAI/deepwiki-open](repos/asyncfuncai-deepwiki-open.md) · ⭐ 14869 · Python · An AI-driven application that generates dynamic wikis and visual architecture...

- [HKUDS/DeepCode](repos/hkuds-deepcode.md) · ⭐ 14865 · Python · A sophisticated multi-agent AI system for automating large-scale software gen...

- [K-Dense-AI/claude-scientific-skills](repos/k-dense-ai-claude-scientific-skills.md) · ⭐ 14687 · Python · A vast repository of over 170 domain-specific skills enabling AI agents to pe...

- [Wan-Video/Wan2.2](repos/wan-video-wan22.md) · ⭐ 14617 · Python · The successor to Wan2.1, featuring a Mixture-of-Experts (MoE) architecture fo...

- [lynx-family/lynx](repos/lynx-family-lynx.md) · ⭐ 14577 · C++ · A high-performance cross-platform UI framework allowing developers to build n...

- [SesameAILabs/csm](repos/sesameailabs-csm.md) · ⭐ 14539 · Python · A state-of-the-art Conversational Speech Model integrating Llama logic with a...

- [2025Emma/vibe-coding-cn](repos/2025emma-vibe-coding-cn.md) · ⭐ 14296 · Python · An extensive Chinese-language guide and framework for optimizing AI-assisted ...

- [youhunwl/TVAPP](repos/youhunwl-tvapp.md) · ⭐ 14277 · JavaScript · A curated collection of Chinese Smart TV applications, TVBox sources, and liv...

- [HKUDS/RAG-Anything](repos/hkuds-rag-anything.md) · ⭐ 14187 · Python · An advanced, all-in-one Retrieval-Augmented Generation (RAG) framework capabl...

- [RightNow-AI/openfang](repos/rightnow-ai-openfang.md) · ⭐ 14098 · Rust · A robust, high-performance open-source Agent Operating System built entirely ...

- [openai/skills](repos/openai-skills.md) · ⭐ 14089 · Python · A collection of predefined Agent Skills to enhance AI agents like Codex and C...

- [shanraisshan/claude-code-best-practice](repos/shanraisshan-claude-code-best-practice.md) · ⭐ 14065 · HTML · An extensive best-practice guide for utilizing Claude Code covering Concepts ...

- [pranshuparmar/witr](repos/pranshuparmar-witr.md) · ⭐ 14063 · Go · A CLI tool that traces process ancestry to answer "Why is this running?", pro...

- [muratcankoylan/Agent-Skills-for-Context-Engineering](repos/muratcankoylan-agent-skills-for-context-engineering.md) · ⭐ 13814 · Python · A repository offering a collection of Agent Skills aimed specifically at opti...

- [coleam00/Archon](repos/coleam00-archon.md) · ⭐ 13757 · Python · Archon functions as a centralized Model Context Protocol (MCP) server managin...

- [elder-plinius/CL4R1T4S](repos/elder-plinius-cl4r1t4s.md) · ⭐ 13741 · — · An archive of leaked or reverse-engineered system prompts from large AI syste...

- [microsoft/edit](repos/microsoft-edit.md) · ⭐ 13656 · Rust · A modern homage to the classic MS-DOS Editor, built with Rust for terminal-ba...

- [Billionmail/BillionMail](repos/billionmail-billionmail.md) · ⭐ 13654 · Go · An open-source mail server and email marketing platform offering unlimited se...

- [GLips/Figma-Context-MCP](repos/glips-figma-context-mcp.md) · ⭐ 13652 · TypeScript · An MCP server that provides AI coding assistants like Cursor direct access to...

- [ConardLi/easy-dataset](repos/conardli-easy-dataset.md) · ⭐ 13617 · JavaScript · An application enabling users to intelligently parse unstructured documents t...

- [VoltAgent/awesome-claude-code-subagents](repos/voltagent-awesome-claude-code-subagents.md) · ⭐ 13604 · Shell · A definitive, community-driven collection of specialized AI subagents crafted...

- [kepano/obsidian-skills](repos/kepano-obsidian-skills.md) · ⭐ 13588 · — · A suite of Agent Skills specifically configured for AI agents to interact wit...

- [memvid/memvid](repos/memvid-memvid.md) · ⭐ 13420 · Rust · A lightning-fast, portable, single-file memory format built in Rust, enabling...

- [Tencent/WeKnora](repos/tencent-weknora.md) · ⭐ 13364 · Go · A comprehensive RAG framework developed by Tencent integrating robust multimo...

- [Tencent-Hunyuan/Hunyuan3D-2](repos/tencent-hunyuan-hunyuan3d-2.md) · ⭐ 13285 · Python · An open-source, large-scale 3D synthesis ecosystem comprised of advanced diff...

- [AndyMik90/Aperant](repos/andymik90-aperant.md) · ⭐ 13247 · TypeScript · Auto Claude represents an autonomous framework using multi-agent capabilities...

- [LibreSpark/LibreTV](repos/librespark-libretv.md) · ⭐ 13216 · JavaScript · LibreTV is a lightweight, open-source online video platform aggregating searc...

- [coreyhaines31/marketingskills](repos/coreyhaines31-marketingskills.md) · ⭐ 13139 · JavaScript · An extensive library of pre-formatted prompts and instruction sets (Agent Ski...

- [jamiepine/voicebox](repos/jamiepine-voicebox.md) · ⭐ 13116 · TypeScript · An open-source, local-first voice synthesis and cloning application functioni...

- [trycua/cua](repos/trycua-cua.md) · ⭐ 13044 · Python · A framework encompassing an SDK and virtual sandbox environments allowing dev...

- [eigent-ai/eigent](repos/eigent-ai-eigent.md) · ⭐ 12971 · TypeScript · An open-source, local-first Cowork desktop application employing a Multi-Agen...

- [agentskills/agentskills](repos/agentskills-agentskills.md) · ⭐ 12947 · Python · An open, standardized specification detailing how to package instructions and...

- [Jiayi-Pan/TinyZero](repos/jiayi-pan-tinyzero.md) · ⭐ 12930 · Python · A reinforcement learning project replicating DeepSeek R1 Zero's reasoning cap...

- [Anionex/banana-slides](repos/anionex-banana-slides.md) · ⭐ 12908 · TypeScript · An AI-powered presentation generator application designed around the Nano Ban...

- [NevaMind-AI/memU](repos/nevamind-ai-memu.md) · ⭐ 12883 · Python · A proactive memory framework acting as a file-system knowledge graph, allowin...

- [google/A2UI](repos/google-a2ui.md) · ⭐ 12847 · TypeScript · An open-source standard and toolkit by Google enabling AI agents to dynamical...

- [snarktank/ralph](repos/snarktank-ralph.md) · ⭐ 12792 · TypeScript · A sophisticated CLI bash loop pattern that continuously spawns fresh instance...

- [coleam00/context-engineering-intro](repos/coleam00-context-engineering-intro.md) · ⭐ 12726 · Python · A philosophical guide highlighting best practices for structuring documentati...

- [facebookresearch/vggt](repos/facebookresearch-vggt.md) · ⭐ 12576 · Python · A state-of-the-art transformer model by Meta AI capable of inferring extremel...

- [deepseek-ai/FlashMLA](repos/deepseek-ai-flashmla.md) · ⭐ 12514 · C++ · A highly specialized repository containing optimized GPU attention kernels en...

- [ag-ui-protocol/ag-ui](repos/ag-ui-protocol-ag-ui.md) · ⭐ 12435 · Python · An open event-based protocol establishing exactly how AI agents connect relia...

- [p-e-w/heretic](repos/p-e-w-heretic.md) · ⭐ 12386 · Python · A sophisticated CLI tool automating directional ablation techniques natively ...

- [vercel-labs/json-render](repos/vercel-labs-json-render.md) · ⭐ 12369 · TypeScript · A framework developed by Vercel constraining AI code generation precisely ont...

- [sapientinc/HRM](repos/sapientinc-hrm.md) · ⭐ 12357 · Python · A highly lightweight recurrent AI model simulating System 1/System 2 thinking...

- [MemoriLabs/Memori](repos/memorilabs-memori.md) · ⭐ 12349 · Python · An infrastructure-agnostic persistence layer enabling AI agents to seamlessly...

- [imputnet/helium](repos/imputnet-helium.md) · ⭐ 12319 · C++ · A highly transparent, user-focused Chromium fork maximizing privacy algorithm...

- [contains-studio/agents](repos/contains-studio-agents.md) · ⭐ 12296 · — · A structured library detailing explicit Claude Code sub-agent instructions co...

- [abhigyanpatwari/GitNexus](repos/abhigyanpatwari-gitnexus.md) · ⭐ 12296 · TypeScript · An intelligent structural analyzer scanning entire source codebases predictin...

- [GeeeekExplorer/nano-vllm](repos/geeeekexplorer-nano-vllm.md) · ⭐ 12189 · Python · An extremely streamlined inferencing engine replicating precise vLLM mechanic...

- [fish2018/pansou](repos/fish2018-pansou.md) · ⭐ 12171 · Go · A high-performance API aggregating comprehensive search capabilities spanning...

- [The-Pocket/PocketFlow-Tutorial-Codebase-Knowledge](repos/the-pocket-pocketflow-tutorial-codebase-knowledge.md) · ⭐ 12135 · Python · An intelligent codebase analysis tool leveraging the PocketFlow LLM framework...

- [openai/symphony](repos/openai-symphony.md) · ⭐ 12085 · Elixir · An experimental multi-agent orchestration framework automating totally the so...

- [alam00000/bentopdf](repos/alam00000-bentopdf.md) · ⭐ 11996 · JavaScript · An incredibly comprehensive fully client-side WASM-powered PDF manipulation s...

- [steveyegge/gastown](repos/steveyegge-gastown.md) · ⭐ 11944 · Go · A sophisticated CLI orchestration manager defining resilient Multi-Agent coll...

- [originalankur/maptoposter](repos/originalankur-maptoposter.md) · ⭐ 11887 · Python · A beautifully elegant Python utility converting explicit geospatial coordinat...

- [rybbit-io/rybbit](repos/rybbit-io-rybbit.md) · ⭐ 11800 · TypeScript · A high-performance real-time AI translation library for low-latency communica...

- [Leey21/awesome-ai-research-writing](repos/leey21-awesome-ai-research-writing.md) · ⭐ 11757 · — · An expertly compiled repository detailing explicit Prompt Engineering techniq...

- [Nagi-ovo/gemini-voyager](repos/nagi-ovo-gemini-voyager.md) · ⭐ 11729 · TypeScript · A sophisticated Chromium extension significantly enhancing exactly the vanill...

- [HKUDS/AI-Trader](repos/hkuds-ai-trader.md) · ⭐ 11678 · Python · An open-source marketplace infrastructure linking autonomously operating fina...

- [different-ai/openwork](repos/different-ai-openwork.md) · ⭐ 11665 · TypeScript · A sophisticated cross-platform application wrapping essentially open-source l...

- [tadata-org/fastapi_mcp](repos/tadata-org-fastapi-mcp.md) · ⭐ 11650 · Python · An incredibly straightforward integration bridge parsing natively Python Fast...

- [xpzouying/xiaohongshu-mcp](repos/xpzouying-xiaohongshu-mcp.md) · ⭐ 11500 · Go · An immensely valuable unoffical MCP server linking accurately major AI system...

- [ryoppippi/ccusage](repos/ryoppippi-ccusage.md) · ⭐ 11495 · TypeScript · An exceptionally fast Node.js utility parsing dynamically Claude Code termina...

- [jd-opensource/joyagent-jdgenie](repos/jd-opensource-joyagent-jdgenie.md) · ⭐ 11422 · Java · An exceptionally advanced comprehensive enterprise-grade Multi-Agent orchestr...

- [yikart/AiToEarn](repos/yikart-aitoearn.md) · ⭐ 11412 · TypeScript · A fully comprehensive omni-channel social media automation matrix mapping exp...

- [HW-whistleblower/True-Story-of-Pangu](repos/hw-whistleblower-true-story-of-pangu.md) · ⭐ 11384 · — · An explosive internal whistle-blower manifesto detailing exactly explicit arc...

- [opencode-ai/opencode](repos/opencode-ai-opencode.md) · ⭐ 11374 · Go · A sophisticated CLI-based AI coding companion resolving perfectly terminal in...

- [KittenML/KittenTTS](repos/kittenml-kittentts.md) · ⭐ 11256 · Python · An ultra-compact CPU-optimized artificial voice generation algorithm executin...

- [BeehiveInnovations/pal-mcp-server](repos/beehiveinnovations-pal-mcp-server.md) · ⭐ 11248 · Python · An extraordinarily sophisticated multi-agent protocol adapter bridging dynami...

- [shiyu-coder/Kronos](repos/shiyu-coder-kronos.md) · ⭐ 11119 · Python · An immensely significant AAAI-accepted foundation model analyzing strictly mu...

- [agentscope-ai/CoPaw](repos/agentscope-ai-copaw.md) · ⭐ 11096 · Python · CoPaw is a versatile, easily deployable personal AI assistant supporting mult...

- [VoltAgent/awesome-agent-skills](repos/voltagent-awesome-agent-skills.md) · ⭐ 11090 · — · A comprehensive repository of curated and community-driven AI agent skills de...

- [bytedance/trae-agent](repos/bytedance-trae-agent.md) · ⭐ 11013 · Python · Trae Agent is a research-friendly CLI tool from ByteDance used to automate di...

- [SparkAudio/Spark-TTS](repos/sparkaudio-spark-tts.md) · ⭐ 10949 · Python · Spark-TTS is a highly efficient text-to-speech system relying on single-strea...

- [NoFxAiOS/nofx](repos/nofxaios-nofx.md) · ⭐ 10874 · Go · NOFX is an autonomous AI crypto and market trading assistant powered by stand...

- [yusufkaraaslan/Skill_Seekers](repos/yusufkaraaslan-skill-seekers.md) · ⭐ 10764 · Python · Skill Seekers is a universal data layer that transforms diverse content sourc...

- [hangwin/mcp-chrome](repos/hangwin-mcp-chrome.md) · ⭐ 10746 · TypeScript · Chrome MCP Server is an extension-based model context protocol server that en...

- [HKUDS/DeepTutor](repos/hkuds-deeptutor.md) · ⭐ 10684 · Python · DeepTutor is a comprehensive AI-powered learning system that combines documen...

- [langchain-ai/deepagents](repos/langchain-ai-deepagents.md) · ⭐ 10661 · Python · Deep Agents is an opinionated, out-of-the-box agent harness built on LangGrap...

- [byJoey/cfnew](repos/byjoey-cfnew.md) · ⭐ 10579 · — · CFnew is an advanced Cloudflare Workers script deploying a multi-protocol (VL...

- [bytebot-ai/bytebot](repos/bytebot-ai-bytebot.md) · ⭐ 10545 · TypeScript · Bytebot is an open-source AI desktop agent that operates within a full virtua...

- [anthropics/claude-plugins-official](repos/anthropics-claude-plugins-official.md) · ⭐ 10509 · Python · This repository serves as the official marketplace for Claude Code plugins, i...

- [MoonshotAI/Kimi-K2](repos/moonshotai-kimi-k2.md) · ⭐ 10498 · — · Kimi K2 is a massive 1-trillion parameter MoE model from Moonshot AI, specifi...

- [Tongyi-MAI/Z-Image](repos/tongyi-mai-z-image.md) · ⭐ 10480 · Python · Z-Image is a high-efficiency 6B image generation model from Alibaba's Tongyi-...

- [Mail-0/Zero](repos/mail-0-zero.md) · ⭐ 10479 · TypeScript · Zero is a privacy-first, open-source AI email client and server that offers a...

- [EveryInc/compound-engineering-plugin](repos/everyinc-compound-engineering-plugin.md) · ⭐ 10331 · TypeScript · EveryInc's plugin marketplace offers a suite of 'Compound Engineering' tools ...

- [yichuan-w/LEANN](repos/yichuan-w-leann.md) · ⭐ 10302 · Python · LEANN is an ultra-lightweight vector database that uses selective recomputati...

- [RunanywhereAI/runanywhere-sdks](repos/runanywhereai-runanywhere-sdks.md) · ⭐ 10246 · C++ · RunAnywhere provides high-performance, cross-platform SDKs for executing LLMs...

- [HKUDS/CLI-Anything](repos/hkuds-cli-anything.md) · ⭐ 10191 · Python · CLI-Anything is an automated tool that transforms any software repository int...

- [iflytek/astron-agent](repos/iflytek-astron-agent.md) · ⭐ 10113 · Java · Astron Agent is an open-source, enterprise-ready platform from iFLYTEK design...

- [vercel-labs/skills](repos/vercel-labs-skills.md) · ⭐ 10011 · TypeScript · Vercel's Skills CLI is a package manager for the open agent ecosystem, allowi...

- [aureuserp/aureuserp](repos/aureuserp-aureuserp.md) · ⭐ 9883 · PHP · Aureus ERP is a modular, high-performance open-source ERP system built on the...

- [KalyanKS-NLP/llm-engineer-toolkit](repos/kalyanks-nlp-llm-engineer-toolkit.md) · ⭐ 9883 · — · The LLM Engineer Toolkit is a comprehensive, categorized resource hub for dev...

- [bytedance/UI-TARS](repos/bytedance-ui-tars.md) · ⭐ 9874 · Python · UI-TARS is a state-of-the-art Vision-Language model from ByteDance that acts ...

- [danielmiessler/Personal_AI_Infrastructure](repos/danielmiessler-personal-ai-infrastructure.md) · ⭐ 9837 · TypeScript · PAI is a premium open-source framework by Daniel Miessler that transforms AI ...

- [nearai/ironclaw](repos/nearai-ironclaw.md) · ⭐ 9816 · Rust · IronClaw is a security-first, Rust-based personal AI assistant that executes ...

- [facebookresearch/dinov3](repos/facebookresearch-dinov3.md) · ⭐ 9813 · Jupyter Notebook · DINOv3 is Meta AI's latest family of self-supervised vision models, ranging f...

- [deepseek-ai/3FS](repos/deepseek-ai-3fs.md) · ⭐ 9766 · C++ · 3FS is a distributed, high-performance file system from DeepSeek-AI, specific...

- [accomplish-ai/accomplish](repos/accomplish-ai-accomplish.md) · ⭐ 9757 · TypeScript · Accomplish is a privacy-first, open-source AI desktop agent for macOS and Win...

- [microsoft/magentic-ui](repos/microsoft-magentic-ui.md) · ⭐ 9717 · Python · Magentic-UI is a Microsoft Research project that provides a transparent, cont...

- [browseros-ai/BrowserOS](repos/browseros-ai-browseros.md) · ⭐ 9707 · C++ · BrowserOS is a specialized, open-source Chromium fork designed to run AI agen...

- [microsoft/vscode-copilot-chat](repos/microsoft-vscode-copilot-chat.md) · ⭐ 9602 · TypeScript · GitHub Copilot Chat is Microsoft's premier AI extension for VS Code, enabling...

- [cloudflare/moltworker](repos/cloudflare-moltworker.md) · ⭐ 9586 · TypeScript · Moltworker is an experimental project that allows developers to host the Open...

- [liyupi/ai-guide](repos/liyupi-ai-guide.md) · ⭐ 9584 · JavaScript · Yupis AI Knowledge Base is a comprehensive, free Chinese resource hub for AI ...

- [ValueCell-ai/valuecell](repos/valuecell-ai-valuecell.md) · ⭐ 9572 · Python · ValueCell is a decentralized, multi-agent AI platform dedicated to financial ...

- [Yeachan-Heo/oh-my-claudecode](repos/yeachan-heo-oh-my-claudecode.md) · ⭐ 9570 · TypeScript · Oh-My-ClaudeCode (OMC) is a powerful, tmux-powered orchestration layer for Cl...

- [jnsahaj/tweakcn](repos/jnsahaj-tweakcn.md) · ⭐ 9532 · TypeScript · Tweakcn is a visual design tool for the shadcn/ui ecosystem, allowing develop...

- [NoeFabris/opencode-antigravity-auth](repos/noefabris-opencode-antigravity-auth.md) · ⭐ 9485 · TypeScript · This Opencode plugin enables Google OAuth, allowing developers to access Anti...

- [vxcontrol/pentagi](repos/vxcontrol-pentagi.md) · ⭐ 9454 · Go · PentAGI is a state-of-the-art, autonomous AI system for penetration testing, ...

- [QwenLM/Qwen3-TTS](repos/qwenlm-qwen3-tts.md) · ⭐ 9447 · Python · Qwen3-TTS is Alibaba's next-generation speech generation series, offering SOT...

- [Wei-Shaw/claude-relay-service](repos/wei-shaw-claude-relay-service.md) · ⭐ 9446 · JavaScript · Claude Relay Service is a self-hosted API gateway for Claude and Codex, featu...

- [mcp-use/mcp-use](repos/mcp-use-mcp-use.md) · ⭐ 9432 · TypeScript · mcp-use is a comprehensive full-stack framework for the Model Context Protoco...

- [Usagi-org/ai-goofish-monitor](repos/usagi-org-ai-goofish-monitor.md) · ⭐ 9399 · Python · Goofish Monitor is an AI-powered real-time tracking tool for the Xianyu (Goof...

- [Open-Dev-Society/OpenStock](repos/open-dev-society-openstock.md) · ⭐ 9378 · TypeScript · OpenStock is an open-source financial dashboard built with Next.js and MongoD...

- [aden-hive/hive](repos/aden-hive-hive.md) · ⭐ 9355 · Python · Aden Hive is a production-ready multi-agent framework that uses a 'Queen Agen...

- [ZeroLu/awesome-nanobanana-pro](repos/zerolu-awesome-nanobanana-pro.md) · ⭐ 9354 · — · Awesome Nano Banana Pro is a comprehensive prompt engineering library for the...

- [anomalyco/opentui](repos/anomalyco-opentui.md) · ⭐ 9344 · TypeScript · OpenTUI is a high-performance, native Terminal UI (TUI) engine written in Zig...

- [saturndec/waoowaoo](repos/saturndec-waoowaoo.md) · ⭐ 9279 · TypeScript · waoowaoo is an AI-powered film studio for short dramas and comics, automating...

- [chaitin/PandaWiki](repos/chaitin-pandawiki.md) · ⭐ 9278 · TypeScript · PandaWiki is an AI-driven, open-source knowledge base system that transforms ...

- [diet103/claude-code-infrastructure-showcase](repos/diet103-claude-code-infrastructure-showcase.md) · ⭐ 9234 · Shell · This repository is a production-hardened reference library for Claude Code in...

- [Arindam200/awesome-ai-apps](repos/arindam200-awesome-ai-apps.md) · ⭐ 9223 · Python · Awesome AI Apps is a curated resource library featuring over 70 practical exa...

- [zarazhangrui/frontend-slides](repos/zarazhangrui-frontend-slides.md) · ⭐ 9216 · CSS · Frontend Slides is an AI-powered UI skill for Claude Code that generates prem...

- [sjzar/chatlog](repos/sjzar-chatlog.md) · ⭐ 9195 · — · Chatlog was an open-source log management tool that has been discontinued and...

- [rowboatlabs/rowboat](repos/rowboatlabs-rowboat.md) · ⭐ 9174 · TypeScript · Rowboat is a local-first AI coworker that integrates with your email and meet...

- [deepseek-ai/DeepEP](repos/deepseek-ai-deepep.md) · ⭐ 9045 · Cuda · DeepEP is a specialized GPU communication library for MoE architectures, prov...

- [anthropics/knowledge-work-plugins](repos/anthropics-knowledge-work-plugins.md) · ⭐ 9022 · Python · Knowledge Work Plugins is an open-source marketplace of 11 role-specific plug...

- [OpenPipe/ART](repos/openpipe-art.md) · ⭐ 9011 · Python · ART (Agent Reinforcement Trainer) is an open-source RL framework that enables...

- [numman-ali/openskills](repos/numman-ali-openskills.md) · ⭐ 8997 · TypeScript · OpenSkills is a universal CLI tool that brings Anthropic's 'Skills' system to...

- [53AI/53AIHub](repos/53ai-53aihub.md) · ⭐ 8928 · Go · 53AI Hub is an open-source AI management portal enabling enterprises to deplo...

- [blader/humanizer](repos/blader-humanizer.md) · ⭐ 8921 · — · Humanizer is a professional-grade text refinement skill for Claude Code that ...

- [huggingface/skills](repos/huggingface-skills.md) · ⭐ 8911 · Python · Hugging Face Skills is a collection of standardized definitions for AI/ML wor...

- [alibaba/zvec](repos/alibaba-zvec.md) · ⭐ 8904 · C++ · Zvec is a high-performance, in-process vector database built on the Proxima e...

- [xinnan-tech/xiaozhi-esp32-server](repos/xinnan-tech-xiaozhi-esp32-server.md) · ⭐ 8864 · JavaScript · Xiaozhi-esp32-server is a comprehensive backend for open-source AI hardware, ...

- [bytedance/Dolphin](repos/bytedance-dolphin.md) · ⭐ 8859 · Python · Dolphin is an advanced Document Image Parsing model that handles digital and ...

- [Panniantong/Agent-Reach](repos/panniantong-agent-reach.md) · ⭐ 8851 · Python · Agent Reach is a 'scaffolding' tool that equips AI coding agents with powerfu...

- [cft0808/edict](repos/cft0808-edict.md) · ⭐ 8838 · Python · Edict (San Sheng Liu Bu) is a highly structured multi-agent framework that im...

- [chatfire-AI/huobao-drama](repos/chatfire-ai-huobao-drama.md) · ⭐ 8800 · Vue · Huobao Drama is an end-to-end AI production platform that transforms ideas in...

- [KrishKrosh/TrackWeight](repos/krishkrosh-trackweight.md) · ⭐ 8756 · Swift · TrackWeight is an innovative macOS utility that repurposes the Force Touch tr...

- [travisvn/awesome-claude-skills](repos/travisvn-awesome-claude-skills.md) · ⭐ 8756 · — · Awesome Claude Skills is a comprehensive repository of resources, tutorials, ...

- [JimLiu/baoyu-skills](repos/jimliu-baoyu-skills.md) · ⭐ 8738 · TypeScript · Baoyu Skills is a premium toolkit for Claude Code, offering specialized modul...

- [YouMind-OpenLab/awesome-nano-banana-pro-prompts](repos/youmind-openlab-awesome-nano-banana-pro-prompts.md) · ⭐ 8675 · TypeScript · A comprehensive collection of visual and creative prompts optimized for Googl...

- [google/adk-samples](repos/google-adk-samples.md) · ⭐ 8660 · Python · The official collection of multi-language sample agents built using Google's ...

- [HKUDS/AutoAgent](repos/hkuds-autoagent.md) · ⭐ 8654 · Python · A zero-code framework for building and orchestrating autonomous LLM agents an...

- [antiwork/gumroad](repos/antiwork-gumroad.md) · ⭐ 8613 · Ruby · The open-source core platform of Gumroad, a major e-commerce tool for the cre...

- [davidkimai/Context-Engineering](repos/davidkimai-context-engineering.md) · ⭐ 8557 · Python · A comprehensive guide and curriculum for mastering the design and optimizatio...

- [awslabs/mcp](repos/awslabs-mcp.md) · ⭐ 8437 · Python · A collection of open-source Model Context Protocol (MCP) servers providing sp...

- [apple/containerization](repos/apple-containerization.md) · ⭐ 8395 · Swift · A Swift framework for managing and running Linux containers on macOS via Virt...

- [siteboon/claudecodeui](repos/siteboon-claudecodeui.md) · ⭐ 8357 · TypeScript · A web-based graphical user interface for popular AI coding CLIs, enabling cro...

- [lukilabs/beautiful-mermaid](repos/lukilabs-beautiful-mermaid.md) · ⭐ 8226 · TypeScript · A high-performance, dependency-free Mermaid diagram renderer for TypeScript/J...

- [facebookresearch/sam3](repos/facebookresearch-sam3.md) · ⭐ 8145 · Python · Meta's next-generation 'Segment Anything' model adding open-vocabulary concep...

- [MoonTechLab/LunaTV](repos/moontechlab-lunatv.md) · ⭐ 8083 · TypeScript · A cross-platform, self-hosted media aggregation player built with Next.js 14,...

- [caelestia-dots/shell](repos/caelestia-dots-shell.md) · ⭐ 8064 · QML · A modern, widget-based desktop shell for Linux built with Quickshell and opti...

- [datahaven-xyz/datahaven](repos/datahaven-xyz-datahaven.md) · ⭐ 8036 · Rust · A decentralized storage network optimized for AI data and models, leveraging ...

- [OpenHub-Store/GitHub-Store](repos/openhub-store-github-store.md) · ⭐ 8022 · Kotlin · An open-source 'App Store' for GitHub releases, facilitating discovery and in...

- [rednote-hilab/dots.ocr](repos/rednote-hilab-dotsocr.md) · ⭐ 7998 · Python · A state-of-the-art multilingual OCR and image parsing model that converts doc...

- [boson-ai/higgs-audio](repos/boson-ai-higgs-audio.md) · ⭐ 7975 · Python · A state-of-the-art 3.6B parameter audio foundation model for expressive text-...

- [deepseek-ai/open-infra-index](repos/deepseek-ai-open-infra-index.md) · ⭐ 7974 · — · A central index for DeepSeek's high-performance infrastructure components, in...

- [steipete/CodexBar](repos/steipete-codexbar.md) · ⭐ 7934 · Swift · A macOS menu bar utility for monitoring usage limits and credits across multi...

- [droidrun/droidrun](repos/droidrun-droidrun.md) · ⭐ 7932 · Python · A framework for building mobile device agents that can control Android and iO...

- [LaurieWired/GhidraMCP](repos/lauriewired-ghidramcp.md) · ⭐ 7900 · Java · An MCP server that bridges Ghidra's reverse engineering tools with LLM agents...

- [microsoft/agent-framework](repos/microsoft-agent-framework.md) · ⭐ 7885 · Python · Microsoft Agent Framework provides a unified approach to building and deployi...

- [siddharthvaddem/openscreen](repos/siddharthvaddem-openscreen.md) · ⭐ 7882 · TypeScript · An open-source, free-to-use screen recording application designed as a simple...

- [jamez-bondos/awesome-gpt4o-images](repos/jamez-bondos-awesome-gpt4o-images.md) · ⭐ 7862 · JavaScript · A curated awesome list of images and prompt examples generated by OpenAI's GP...

- [apple/ml-sharp](repos/apple-ml-sharp.md) · ⭐ 7853 · Python · SHARP is a neural network model that rapidly converts a single 2D photograph ...

- [github/copilot-sdk](repos/github-copilot-sdk.md) · ⭐ 7783 · TypeScript · A programmable SDK (for Python, TypeScript, Go, and .NET) exposing the produc...

- [frankbria/ralph-claude-code](repos/frankbria-ralph-claude-code.md) · ⭐ 7781 · Shell · Ralph is a wrapper for Claude Code that enables safe, continuous, and autonom...

- [mmulet/term.everything](repos/mmulet-termeverything.md) · ⭐ 7774 · Go · term.everything is a Linux CLI tool that functions as a from-scratch Wayland ...

- [bytedance/flowgram.ai](repos/bytedance-flowgramai.md) · ⭐ 7770 · TypeScript · ByteDance's visual, node-based development environment for orchestrating comp...

- [idosal/git-mcp](repos/idosal-git-mcp.md) · ⭐ 7756 · TypeScript · An MCP (Model Context Protocol) server that grants AI assistants direct acces...

- [ace-step/ACE-Step-1.5](repos/ace-step-ace-step-15.md) · ⭐ 7744 · Python · A highly efficient open-source music foundation model producing commercial-gr...

- [volcengine/OpenViking](repos/volcengine-openviking.md) · ⭐ 7722 · Python · An open-source Context Database solving AI Agent fragmentation by mapping doc...

- [zilliztech/deep-searcher](repos/zilliztech-deep-searcher.md) · ⭐ 7700 · Python · Zilliztech's deep content search and semantic indexing framework for massive ...

- [alibaba/OpenSandbox](repos/alibaba-opensandbox.md) · ⭐ 7685 · Python · OpenSandbox is Alibaba's open-source sandbox infrastructure platform providin...

- [automazeio/ccpm](repos/automazeio-ccpm.md) · ⭐ 7626 · Shell · CCPM (Claude Code PM) is a battle-tested project management system for Claude...

- [snarktank/ai-dev-tasks](repos/snarktank-ai-dev-tasks.md) · ⭐ 7622 · — · A set of structured markdown prompt files (`create-prd.md`, `generate-tasks.m...

- [zumerlab/snapdom](repos/zumerlab-snapdom.md) · ⭐ 7603 · JavaScript · SnapDOM is a zero-dependency JavaScript library for capturing DOM elements as...

- [QwenLM/Qwen-Image](repos/qwenlm-qwen-image.md) · ⭐ 7545 · Python · Qwen-Image is Alibaba's 20B parameter multimodal diffusion transformer for te...

- [LuckyOne7777/LLM-Trading-Lab](repos/luckyone7777-llm-trading-lab.md) · ⭐ 7423 · Python · A transparent, forward-only research framework documenting a live experiment ...

- [0x4m4/hexstrike-ai](repos/0x4m4-hexstrike-ai.md) · ⭐ 7418 · Python · HexStrike AI is an MCP-based cybersecurity automation platform integrating 15...

- [BehiSecc/awesome-claude-skills](repos/behisecc-awesome-claude-skills.md) · ⭐ 7399 · — · A community-curated awesome list of over 100 Claude Code skills (SKILL.md fil...

- [aliasrobotics/cai](repos/aliasrobotics-cai.md) · ⭐ 7392 · Python · CAI is the de-facto open-source framework for AI-powered cybersecurity, suppo...

- [GetStream/Vision-Agents](repos/getstream-vision-agents.md) · ⭐ 7367 · Python · Vision Agents is an open-source Python framework by GetStream for building re...

- [GoogleCloudPlatform/kubectl-ai](repos/googlecloudplatform-kubectl-ai.md) · ⭐ 7357 · Go · An official kubectl plugin that allows developers to manage, troubleshoot, an...

- [forrestchang/andrej-karpathy-skills](repos/forrestchang-andrej-karpathy-skills.md) · ⭐ 7355 · — · A single CLAUDE.md (or Claude Code plugin) encoding four Karpathy-derived pri...

- [pickle-com/glass](repos/pickle-com-glass.md) · ⭐ 7343 · JavaScript · Glass is an open-source macOS desktop AI assistant that captures your screen ...

- [pinchtab/pinchtab](repos/pinchtab-pinchtab.md) · ⭐ 7328 · Go · PinchTab is a self-contained 12MB Go binary that runs as a local HTTP server ...

- [apple/ml-fastvlm](repos/apple-ml-fastvlm.md) · ⭐ 7257 · Python · Apple's CVPR 2025 research introducing FastViTHD, a novel hybrid vision encod...

- [Zyphra/Zonos](repos/zyphra-zonos.md) · ⭐ 7198 · Python · A high-fidelity, open-weight TTS model trained on 200k hours of speech, featu...

- [google/adk-go](repos/google-adk-go.md) · ⭐ 7150 · Go · Google's official Go implementation of the Agent Development Kit (ADK), provi...

- [MoonshotAI/kimi-cli](repos/moonshotai-kimi-cli.md) · ⭐ 7143 · Python · Kimi Code CLI is MoonshotAI's terminal-based AI coding agent that autonomousl...

- [HKUDS/ClawWork](repos/hkuds-clawwork.md) · ⭐ 7130 · Python · ClawWork is an open-source economic survival benchmark from HKUDS where AI ag...

- [AgentDeskAI/browser-tools-mcp](repos/agentdeskai-browser-tools-mcp.md) · ⭐ 7118 · JavaScript · An MCP server that exposes browser developer tools (DOM, Network, Console) to...

- [Snouzy/workout-cool](repos/snouzy-workout-cool.md) · ⭐ 7115 · TypeScript · Workout.cool is a self-hostable, open-source Next.js fitness platform with wo...

- [tigshop/Tigshop](repos/tigshop-tigshop.md) · ⭐ 7108 · PLpgSQL · A modern, enterprise-grade e-commerce backend built with Go, focusing on high...

- [steveiliop56/tinyauth](repos/steveiliop56-tinyauth.md) · ⭐ 7098 · Go · A minimalist, secure authentication server providing JWT-based login, MFA, an...

- [nexmoe/VidBee](repos/nexmoe-vidbee.md) · ⭐ 7097 · TypeScript · VidBee is an open-source Electron desktop app (and Docker-ready web+API) for ...

- [Ripple-TS/ripple](repos/ripple-ts-ripple.md) · ⭐ 7002 · JavaScript · A decentralized communication bus protocol specifically architected for cross...

- [CoplayDev/unity-mcp](repos/coplaydev-unity-mcp.md) · ⭐ 6988 · C# · A bridge protocol connecting the Unity 3D engine with the Model Context Proto...

- [mruniquehacker/Knightbot-MD](repos/mruniquehacker-knightbot-md.md) · ⭐ 6963 · JavaScript · A feature-rich WhatsApp bot built with Node.js, supporting multi-device conne...

- [ZyperWave/ZyperWinOptimize](repos/zyperwave-zyperwinoptimize.md) · ⭐ 6938 · C# · ZyperWin++ is a lightweight Windows optimization desktop tool (v4.1) built in...

- [Maciek-roboblog/Claude-Code-Usage-Monitor](repos/maciek-roboblog-claude-code-usage-monitor.md) · ⭐ 6929 · Python · Claude Code Usage Monitor (`claude-monitor`) is a Python terminal tool that r...

- [Done-0/fuck-u-code](repos/done-0-fuck-u-code.md) · ⭐ 6868 · TypeScript · fuck-u-code is a Node.js CLI tool that analyzes code quality offline using tr...

- [memstechtips/Winhance](repos/memstechtips-winhance.md) · ⭐ 6822 · C# · A comprehensive optimization and debloating toolkit for Windows that improves...

- [karminski/one-small-step](repos/karminski-one-small-step.md) · ⭐ 6807 · Python · A structured educational roadmap for transitioning from software development ...

- [phuryn/pm-skills](repos/phuryn-pm-skills.md) · ⭐ 6807 · — · A Claude Code / Claude Cowork plugin marketplace with 65 product management s...

- [MemTensor/MemOS](repos/memtensor-memos.md) · ⭐ 6797 · Python · MemOS is an open-source Memory Operating System (arXiv 2507.03724) for LLMs a...

- [openai/openai-realtime-agents](repos/openai-openai-realtime-agents.md) · ⭐ 6790 · TypeScript · The official reference library for developers to build ultra-low latency, mul...

- [alibaba/page-agent](repos/alibaba-page-agent.md) · ⭐ 6782 · TypeScript · PageAgent (alibaba/page-agent) is a pure client-side JavaScript library that ...

- [iflytek/astron-rpa](repos/iflytek-astron-rpa.md) · ⭐ 6769 · Java · AstronRPA is an enterprise-grade, open-source RPA platform by iFlytek with 30...

- [vicinaehq/vicinae](repos/vicinaehq-vicinae.md) · ⭐ 6768 · C++ · Vicinae is a fast, keyboard-first, open-source desktop launcher with a React/...

- [superset-sh/superset](repos/superset-sh-superset.md) · ⭐ 6766 · TypeScript · Superset is a macOS Electron desktop terminal application specifically design...

- [francescopace/espectre](repos/francescopace-espectre.md) · ⭐ 6748 · Python · ESPectre is an open-source ESPHome component for ESP32 devices that detects h...

- [lucasgelfond/zerobrew](repos/lucasgelfond-zerobrew.md) · ⭐ 6733 · Rust · zerobrew (`zb`) is an experimental Rust-based Homebrew-compatible package man...

- [MiroMindAI/MiroThinker](repos/miromindai-mirothinker.md) · ⭐ 6714 · Python · MiroThinker is an open-source deep research agent series from MiroMindAI buil...

- [kreuzberg-dev/kreuzberg](repos/kreuzberg-dev-kreuzberg.md) · ⭐ 6688 · Rust · A robust and efficient document parsing library that Extracts plain text and ...

- [VoltAgent/voltagent](repos/voltagent-voltagent.md) · ⭐ 6688 · TypeScript · VoltAgent is a full-stack AI agent platform: an open-source TypeScript framew...

- [rtk-ai/rtk](repos/rtk-ai-rtk.md) · ⭐ 6651 · Rust · rtk is a single Rust binary that intercepts shell command output and applies ...

- [simplescaling/s1](repos/simplescaling-s1.md) · ⭐ 6641 · Python · A research project demonstrating how to achieve state-of-the-art reasoning pe...

- [cloudflare/vinext](repos/cloudflare-vinext.md) · ⭐ 6638 · TypeScript · vinext is an open-source Vite plugin by Cloudflare that reimplements the Next...

- [modelcontextprotocol/registry](repos/modelcontextprotocol-registry.md) · ⭐ 6548 · Go · A central registry and discovery platform where developers can publish and fi...

- [SkyworkAI/SkyReels-V2](repos/skyworkai-skyreels-v2.md) · ⭐ 6547 · Python · SkyReels-V2 is an open-source video generation model series from Skywork comb...

- [Yuliang-Liu/MonkeyOCR](repos/yuliang-liu-monkeyocr.md) · ⭐ 6534 · Python · MonkeyOCR is an open-source document parsing VLM that uses a Structure-Recogn...

- [Lake1059/FFmpegFreeUI](repos/lake1059-ffmpegfreeui.md) · ⭐ 6514 · Visual Basic .NET · FFmpegFreeUI (3FUI) is a professional, ad-free, open-source Windows FFmpeg GU...

- [aidenybai/react-grab](repos/aidenybai-react-grab.md) · ⭐ 6507 · TypeScript · react-grab is a lightweight JavaScript library that adds an element inspector...

- [stagewise-io/stagewise](repos/stagewise-io-stagewise.md) · ⭐ 6505 · TypeScript · stagewise is a desktop browser for developers that ships with a built-in AI c...

- [Jeffallan/claude-skills](repos/jeffallan-claude-skills.md) · ⭐ 6488 · Python · Claude Skills is a powerful extension framework for Claude Code that provides...

- [yzfly/Awesome-MCP-ZH](repos/yzfly-awesome-mcp-zh.md) · ⭐ 6486 · — · Awesome-MCP-ZH is a curated list of resources for the Model Context Protocol ...

- [grab/cursor-talk-to-figma-mcp](repos/grab-cursor-talk-to-figma-mcp.md) · ⭐ 6474 · JavaScript · An MCP server enabling Cursor or other AI editors to directly read and manipu...

- [NousResearch/hermes-agent](repos/nousresearch-hermes-agent.md) · ⭐ 6464 · Python · Hermes Agent is an advanced AI agent framework that features a built-in learn...

- [Jackywine/Bella](repos/jackywine-bella.md) · ⭐ 6446 · JavaScript · Bella AI is a digital companion project designed to create a personalized, ev...

- [nicobailon/visual-explainer](repos/nicobailon-visual-explainer.md) · ⭐ 6446 · HTML · Visual Explainer is a specialized skill for AI agents (compatible with Claude...

- [cocoindex-io/cocoindex](repos/cocoindex-io-cocoindex.md) · ⭐ 6438 · Rust · A real-time, high-throughput indexing system for AI applications requiring up...

- [nikopueringer/CorridorKey](repos/nikopueringer-corridorkey.md) · ⭐ 6427 · Python · CorridorKey is a specialized AI keying engine that solves the 'unmixing' prob...

- [SamsungSAILMontreal/TinyRecursiveModels](repos/samsungsailmontreal-tinyrecursivemodels.md) · ⭐ 6400 · Python · Tiny Recursive Models (TRM) is a research project demonstrating that massive ...

- [NVIDIA/Isaac-GR00T](repos/nvidia-isaac-gr00t.md) · ⭐ 6392 · Jupyter Notebook · NVIDIA's general-purpose foundation model for humanoid robot control and real...

- [Sjj1024/PakePlus-Android](repos/sjj1024-pakeplus-android.md) · ⭐ 6390 · Lua · PakePlus is a cross-platform packaging tool that converts websites into light...

- [pbakaus/impeccable](repos/pbakaus-impeccable.md) · ⭐ 6383 · JavaScript · Impeccable is a specialized extension for AI coding agents (like Cursor and C...

- [AnmolSaini16/mapcn](repos/anmolsaini16-mapcn.md) · ⭐ 6354 · TypeScript · mapcn is a collection of React components for integrating powerful maps into ...

- [punkpeye/awesome-mcp-clients](repos/punkpeye-awesome-mcp-clients.md) · ⭐ 6344 · — · The primary community index for finding and comparing Model Context Protocol ...

- [mrexodia/ida-pro-mcp](repos/mrexodia-ida-pro-mcp.md) · ⭐ 6328 · Python · IDA Pro MCP is a Bridge between IDA Pro and AI assistants using the Model Con...

- [smtg-ai/claude-squad](repos/smtg-ai-claude-squad.md) · ⭐ 6324 · Go · A multi-agent framework that instantiates expert teams to solve complex tasks...

- [fluxerapp/fluxer](repos/fluxerapp-fluxer.md) · ⭐ 6287 · TypeScript · Fluxer is a modern, privacy-focused instant messaging and voice-over-IP (VoIP...

- [anus-dev/ANUS](repos/anus-dev-anus.md) · ⭐ 6278 · TypeScript · An experimental security protocol that uses neural weight matrices as unique,...

- [t3dotgg/stripe-recommendations](repos/t3dotgg-stripe-recommendations.md) · ⭐ 6255 · — · A best-practices guide and reference implementation for 'split-brain' Stripe ...

- [deepseek-ai/DeepGEMM](repos/deepseek-ai-deepgemm.md) · ⭐ 6254 · Cuda · DeepSeek's high-performance FP8 GEMM (General Matrix Multiplication) library ...

- [ai-dynamo/dynamo](repos/ai-dynamo-dynamo.md) · ⭐ 6247 · Rust · An adaptive load-balancing algorithm designed to dynamically distribute AI ta...

- [nullclaw/nullclaw](repos/nullclaw-nullclaw.md) · ⭐ 6244 · Zig · NullClaw is an extremely high-performance, lightweight AI assistant core writ...

- [anthropics/claude-code-action](repos/anthropics-claude-code-action.md) · ⭐ 6235 · TypeScript · Claude Code Action integrates the capabilities of Claude Code directly into G...

- [hotheadhacker/no-as-a-service](repos/hotheadhacker-no-as-a-service.md) · ⭐ 6233 · JavaScript · No-as-a-Service (NaaS) is a fun, utility API that provides witty ways to say ...

- [steipete/gogcli](repos/steipete-gogcli.md) · ⭐ 6232 · Go · gogcli (gog) is a comprehensive command-line interface for Google services in...

- [facebookresearch/sam-3d-objects](repos/facebookresearch-sam-3d-objects.md) · ⭐ 6197 · Python · SAM 3D Objects is part of Meta's SAM 3D family of models. It is a foundation ...

- [nickscamara/open-deep-research](repos/nickscamara-open-deep-research.md) · ⭐ 6191 · TypeScript · An open-source implementation of a multi-agent research system that can brows...

- [kijai/ComfyUI-WanVideoWrapper](repos/kijai-comfyui-wanvideowrapper.md) · ⭐ 6162 · Python · A ComfyUI wrapper for the Wan video generation family, enabling seamless high...

- [nlweb-ai/NLWeb](repos/nlweb-ai-nlweb.md) · ⭐ 6162 · Python · NLWeb is an open protocol designed to bring natural language interfaces to th...

- [maderix/ANE](repos/maderix-ane.md) · ⭐ 6151 · Objective-C · ANE Training is a ground-breaking research project that bypasses Apple's 'inf...

- [OpenBMB/VoxCPM](repos/openbmb-voxcpm.md) · ⭐ 6123 · Python · VoxCPM is an advanced Text-to-Speech (TTS) framework that models speech in a ...

- [pingdotgg/t3code](repos/pingdotgg-t3code.md) · ⭐ 6113 · TypeScript · T3 Code is a lightweight, web-based graphical interface designed for AI codin...

- [tanweai/pua](repos/tanweai-pua.md) · ⭐ 6113 · HTML · PUA (Pick-Up Artist) Skill is a unique personality and methodology plugin for...

- [superdesigndev/superdesign](repos/superdesigndev-superdesign.md) · ⭐ 6097 · TypeScript · SuperDesign is an IDE extension (VS Code, Cursor, Windsurf) that acts as a de...

- [multimodal-art-projection/YuE](repos/multimodal-art-projection-yue.md) · ⭐ 6083 · Python · A state-of-the-art music foundation model capable of generating full, high-fi...

- [bytedance/MegaTTS3](repos/bytedance-megatts3.md) · ⭐ 6073 · Python · ByteDance's next-generation zero-shot TTS model for ultra-realistic voice clo...

- [BrowserMCP/mcp](repos/browsermcp-mcp.md) · ⭐ 6039 · TypeScript · Browser MCP is a specialized Model Context Protocol (MCP) server that connect...

- [tonyantony300/alt-sendme](repos/tonyantony300-alt-sendme.md) · ⭐ 6020 · TypeScript · AltSendme is a modern file sharing application built with Rust and Tauri. It ...

- [canopyai/Orpheus-TTS](repos/canopyai-orpheus-tts.md) · ⭐ 6000 · Python · An AI voice engine specializing in classical, retro, and vintage vocal styles...

- [tbphp/gpt-load](repos/tbphp-gpt-load.md) · ⭐ 5985 · Go · GPT-Load is a Go-based proxy service for managing multiple AI API providers (...

- [databasus/databasus](repos/databasus-databasus.md) · ⭐ 5979 · Go · Databasus is a professional-grade database backup manager. It allows develope...

- [11cafe/jaaz](repos/11cafe-jaaz.md) · ⭐ 5973 · TypeScript · Jaaz.app is an infinite canvas platform where AI agents help users create vis...

- [hexgrad/kokoro](repos/hexgrad-kokoro.md) · ⭐ 5954 · JavaScript · A revolutionary, lightweight (82M parameters) TTS model that achieves state-o...

- [GoogleCloudPlatform/agent-starter-pack](repos/googlecloudplatform-agent-starter-pack.md) · ⭐ 5945 · Python · A comprehensive collection of templates, best practices, and infrastructure-a...

- [openai/openai-cs-agents-demo](repos/openai-openai-cs-agents-demo.md) · ⭐ 5928 · Python · This repository is an official demo from OpenAI showcasing multi-agent orches...

- [nicotsx/zerobyte](repos/nicotsx-zerobyte.md) · ⭐ 5902 · TypeScript · Zerobyte is a user-friendly management layer for the Restic backup engine. It...

- [CyberTimon/RapidRAW](repos/cybertimon-rapidraw.md) · ⭐ 5878 · TypeScript · RapidRAW is a high-performance RAW image editor built with Rust and GPU accel...

- [om-ai-lab/VLM-R1](repos/om-ai-lab-vlm-r1.md) · ⭐ 5865 · Python · A multimodal foundation model that applies DeepSeek-R1's reasoning techniques...

- [roboflow/rf-detr](repos/roboflow-rf-detr.md) · ⭐ 5860 · Python · Roboflow's optimized implementation of the DETR object detection model for ed...

- [santinic/audiblez](repos/santinic-audiblez.md) · ⭐ 5837 · Python · A CLI tool that uses local or remote AI models (like Kokoro or OpenAI) to con...

- [vudovn/antigravity-kit](repos/vudovn-antigravity-kit.md) · ⭐ 5836 · TypeScript · Antigravity Kit is a comprehensive suite of tools for building and deploying ...

- [JerryZLiu/Dayflow](repos/jerryzliu-dayflow.md) · ⭐ 5834 · Swift · Dayflow is a macOS application that automatically tracks and categorizes your...

- [henrythe9th/AI-Crash-Course](repos/henrythe9th-ai-crash-course.md) · ⭐ 5824 · — · A comprehensive fast-track course for mastering full-stack AI application dev...

- [Piebald-AI/claude-code-system-prompts](repos/piebald-ai-claude-code-system-prompts.md) · ⭐ 5794 · JavaScript · This repository tracks and analyzes the system prompts used by Anthropic's Cl...

- [anthropics/financial-services-plugins](repos/anthropics-financial-services-plugins.md) · ⭐ 5785 · Python · A collection of specialized plugins designed to empower Claude for financial ...

- [openclaw/clawhub](repos/openclaw-clawhub.md) · ⭐ 5743 · TypeScript · ClawHub is a public registry for publishing, versioning, and discovering text...

- [afkarxyz/SpotiFLAC](repos/afkarxyz-spotiflac.md) · ⭐ 5740 · TypeScript · A utility that fetches high-fidelity (FLAC) audio versions of Spotify tracks ...

- [shaxiu/XianyuAutoAgent](repos/shaxiu-xianyuautoagent.md) · ⭐ 5740 · Python · An autonomous trading and customer service agent specifically optimized for t...

- [ByteDance-Seed/Bagel](repos/bytedance-seed-bagel.md) · ⭐ 5737 · Python · BAGEL is a 7B-parameter multimodal foundation model (14B total using MoE) cap...

- [NVIDIA/personaplex](repos/nvidia-personaplex.md) · ⭐ 5734 · Python · PersonaPlex is a real-time speech-to-speech conversational model that allows ...

- [millionco/react-doctor](repos/millionco-react-doctor.md) · ⭐ 5708 · TypeScript · React Doctor is an automated diagnostic tool that scans React codebases for s...

- [manaflow-ai/cmux](repos/manaflow-ai-cmux.md) · ⭐ 5690 · Swift · cmux is a native macOS terminal optimized for parallel AI coding sessions. It...

- [dataease/SQLBot](repos/dataease-sqlbot.md) · ⭐ 5674 · JavaScript · SQLBot is an intelligent question-answering system based on LLMs and RAG, spe...

- [UfoMiao/zcf](repos/ufomiao-zcf.md) · ⭐ 5669 · TypeScript · ZCF (Zero-Config Code Flow) is a terminal-based tool for the rapid setup and ...

- [Klavis-AI/klavis](repos/klavis-ai-klavis.md) · ⭐ 5661 · Python · Klavis provides a platform for managing and optimizing AI agent interactions ...

- [sammwyy/MikuMikuBeam](repos/sammwyy-mikumikubeam.md) · ⭐ 5657 · Go · A lightweight and low-latency live streaming server supporting RTMP, HLS, and...

- [coinbase/x402](repos/coinbase-x402.md) · ⭐ 5648 · TypeScript · x402 is an open protocol designed to bring seamless, internet-native payments...

- [DearVa/Everywhere](repos/dearva-everywhere.md) · ⭐ 5647 · C# · Everywhere is a context-aware AI assistant that can perceive and understand a...

- [steipete/agent-rules](repos/steipete-agent-rules.md) · ⭐ 5632 · Shell · This was a historical repository containing guidelines and rule sets for AI a...

- [zilliztech/claude-context](repos/zilliztech-claude-context.md) · ⭐ 5625 · TypeScript · Claude Context is an MCP (Model Context Protocol) plugin that enables semanti...

- [bellard/mquickjs](repos/bellard-mquickjs.md) · ⭐ 5623 · C · MicroQuickJS (MQuickJS) is an ultra-lightweight JavaScript engine designed fo...

- [algorithmicsuperintelligence/openevolve](repos/algorithmicsuperintelligence-openevolve.md) · ⭐ 5603 · Python · OpenEvolve is a sophisticated system that turns LLMs into autonomous code opt...

- [andrewyng/context-hub](repos/andrewyng-context-hub.md) · ⭐ 5598 · JavaScript · Context Hub (Chub) is a specialized registry designed for AI coding agents to...

- [ThinkInAIXYZ/deepchat](repos/thinkinaixyz-deepchat.md) · ⭐ 5576 · TypeScript · A visualization-first chat platform designed to expose and interact with LLM ...

- [wassupjay/n8n-free-templates](repos/wassupjay-n8n-free-templates.md) · ⭐ 5552 · — · This repository is a massive collection of over 200 production-ready n8n work...

- [Sjj1024/PakePlus-iOS](repos/sjj1024-pakeplus-ios.md) · ⭐ 5547 · Swift · PakePlus is a cross-platform tool that packages any website or web app (Vue/R...

- [ngxson/smolvlm-realtime-webcam](repos/ngxson-smolvlm-realtime-webcam.md) · ⭐ 5531 · HTML · This is a minimalist demo showing how to achieve real-time object detection i...

- [dontriskit/awesome-ai-system-prompts](repos/dontriskit-awesome-ai-system-prompts.md) · ⭐ 5518 · TypeScript · A curated collection of elite system prompts and model instructions from top-...

- [ChrisWiles/claude-code-showcase](repos/chriswiles-claude-code-showcase.md) · ⭐ 5506 · JavaScript · This project showcases how to maximize the potential of Claude Code by buildi...

- [facebook/pyrefly](repos/facebook-pyrefly.md) · ⭐ 5460 · Rust · Pyrefly is a high-performance Python type checker and LSP (Language Server Pr...

- [OpenBMB/UltraRAG](repos/openbmb-ultrarag.md) · ⭐ 5459 · Python · A high-performance RAG framework designed for enterprise-scale retrieval, sup...

- [KaringX/clashmi](repos/karingx-clashmi.md) · ⭐ 5447 · Dart · Clash Mi is a cross-platform proxy client built with Flutter, using the mihom...

- [pshenok/server-survival](repos/pshenok-server-survival.md) · ⭐ 5438 · JavaScript · Server Survival is an educational 3D game where players act as Cloud Architec...

- [BlockRunAI/ClawRouter](repos/blockrunai-clawrouter.md) · ⭐ 5434 · TypeScript · ClawRouter is an intelligent LLM gateway that automatically routes AI request...

- [lharries/whatsapp-mcp](repos/lharries-whatsapp-mcp.md) · ⭐ 5405 · Go · This MCP (Model Context Protocol) server bridges personal WhatsApp accounts w...

- [anthropics/claude-agent-sdk-python](repos/anthropics-claude-agent-sdk-python.md) · ⭐ 5394 · Python · This SDK provides a streamlined interface for developers to build interactive...

- [teng-lin/notebooklm-py](repos/teng-lin-notebooklm-py.md) · ⭐ 5382 · Python · NotebookLM-py is a comprehensive, unofficial Python SDK and CLI for Google's ...

- [SamuelSchmidgall/AgentLaboratory](repos/samuelschmidgall-agentlaboratory.md) · ⭐ 5374 · Python · An autonomous agentic laboratory for scientific research and automated paper ...

- [winfunc/deepreasoning](repos/winfunc-deepreasoning.md) · ⭐ 5367 · Rust · An open repository exploring DeepSeek-R1 style reasoning benchmarks and infer...

- [coze-dev/coze-loop](repos/coze-dev-coze-loop.md) · ⭐ 5354 · Go · Coze Loop is a platform-level solution for the full lifecycle management of A...

- [justlovemaki/AIClient-2-API](repos/justlovemaki-aiclient-2-api.md) · ⭐ 5337 · JavaScript · AIClient-2-API is a sophisticated proxy server that bypasses 'client-only' re...

- [strands-agents/sdk-python](repos/strands-agents-sdk-python.md) · ⭐ 5302 · Python · Strands Agents is a lightweight Python SDK for building autonomous AI agents ...

- [donlon/cloudflare-error-page](repos/donlon-cloudflare-error-page.md) · ⭐ 5299 · HTML · This project is an error page generator that creates pixel-perfect replicas o...

- [JefferyHcool/BiliNote](repos/jefferyhcool-bilinote.md) · ⭐ 5289 · Python · BiliNote is an open-source tool that uses AI to summarize videos from Bilibil...

- [langchain-ai/open-swe](repos/langchain-ai-open-swe.md) · ⭐ 5287 · Python · Open SWE is an industrial-grade framework for building 'Software Engineering'...

- [StrayMeteor3337/WechatRealFriends](repos/straymeteor3337-wechatrealfriends.md) · ⭐ 5277 · JavaScript · An AI-driven WeChat social analysis tool that identifies true interaction fre...

- [ghuntley/how-to-build-a-coding-agent](repos/ghuntley-how-to-build-a-coding-agent.md) · ⭐ 5264 · Go · This project is a high-quality educational repository that guides developers ...

- [IAmTomShaw/f1-race-replay](repos/iamtomshaw-f1-race-replay.md) · ⭐ 5239 · Python · F1 Race Replay is a Python-based interactive visualization tool for Formula 1...

- [rllm-org/rllm](repos/rllm-org-rllm.md) · ⭐ 5219 · Python · A comprehensive framework for training LLM agents using Reinforcement Learnin...

- [lintsinghua/DeepAudit](repos/lintsinghua-deepaudit.md) · ⭐ 5209 · Python · XCodeReviewer (formerly DeepAudit) is a sophisticated code auditing platform ...

- [21st-dev/1code](repos/21st-dev-1code.md) · ⭐ 5206 · TypeScript · 1Code is a powerful, open-source desktop client for running AI coding agents....

- [bwya77/vscode-dark-islands](repos/bwya77-vscode-dark-islands.md) · ⭐ 5202 · PowerShell · Islands Dark is a highly customized VS Code theme that transforms the editor'...

- [permissionlesstech/bitchat-android](repos/permissionlesstech-bitchat-android.md) · ⭐ 5193 · Kotlin · Bitchat for Android is a decentralized messaging client that operates entirel...

- [smartcmd/MinecraftConsoles](repos/smartcmd-minecraftconsoles.md) · ⭐ 5184 · C++ · MinecraftConsoles is a community-driven project that preserves and improves t...

- [orion-lib/OrionTV](repos/orion-lib-oriontv.md) · ⭐ 5149 · TypeScript · OrionTV is a modern, cross-platform video playback application designed speci...

- [AmanVarshney01/create-better-t-stack](repos/amanvarshney01-create-better-t-stack.md) · ⭐ 5123 · TypeScript · The modern full-stack TypeScript project boilerplate (T-Stack) optimized for ...

- [sohzm/cheating-daddy](repos/sohzm-cheating-daddy.md) · ⭐ 5118 · JavaScript · Cheating Daddy is an AI-powered personal assistant designed to provide real-t...

- [jina-ai/node-DeepResearch](repos/jina-ai-node-deepresearch.md) · ⭐ 5116 · TypeScript · A Node.js framework for building autonomous research agents that perform deep...

- [MrLesk/Backlog.md](repos/mrlesk-backlogmd.md) · ⭐ 5113 · TypeScript · Backlog.md is a zero-config task management system that lives entirely within...

- [ashishps1/learn-ai-engineering](repos/ashishps1-learn-ai-engineering.md) · ⭐ 5097 · — · Learn AI Engineering is a massive, curated roadmap and resource collection fo...

- [Kodezi/Chronos](repos/kodezi-chronos.md) · ⭐ 5078 · Java · Kodezi Chronos is a specialized language model designed specifically for auto...

- [tiagozip/cap](repos/tiagozip-cap.md) · ⭐ 5063 · JavaScript · A high-performance, open-source screen recording application for macOS built ...

- [Wei-Shaw/sub2api](repos/wei-shaw-sub2api.md) · ⭐ 5060 · Go · Sub2API is a sophisticated AI API gateway platform tailored for distributing ...

- [volcengine/MineContext](repos/volcengine-minecontext.md) · ⭐ 5050 · Python · MineContext is an open-source, proactive AI assistant platform built by ByteD...

- [dwzhu-pku/PaperBanana](repos/dwzhu-pku-paperbanana.md) · ⭐ 5046 · Python · PaperBanana is a sophisticated multi-agent framework designed to automate the...

- [maillab/cloud-mail](repos/maillab-cloud-mail.md) · ⭐ 5040 · JavaScript · Cloud Mail is a lightweight, serverless email platform that leverages the Clo...

- [ln-dev7/square-ui](repos/ln-dev7-square-ui.md) · ⭐ 5033 · TypeScript · Square UI is a curated collection of high-quality, professional landing page ...

- [iflow-ai/iflow-cli](repos/iflow-ai-iflow-cli.md) · ⭐ 5021 · Shell · iFlow CLI is an advanced terminal-based AI assistant comparable to Claude Cod...

- [HisMax/RedInk](repos/hismax-redink.md) · ⭐ 5008 · Python · RedInk is a specialized AI tool designed for creators on platforms like Xiaoh...

- [hellodigua/ChatLab](repos/hellodigua-chatlab.md) · ⭐ 5001 · TypeScript · ChatLab is a desktop application for analyzing and exploring personal social ...
